dist: jammy
language: node_js
node_js:
  - lts/*
cache:
  yarn: true
cache:
  - node_modules
before_install:
  - export START_TIME=$( date +%s )
  - npm i -g yarn
install:
  - yarn install
script:
  - yarn run test
  - yarn run lint
after_script:
  - export END_TIME=$( date +%s )
  - ckeditor5-dev-ci-notify-travis-status
