packages:
  - packages/*

allowBuilds:
  'esbuild': true
  'unrs-resolver': true
  'snyk': true

overrides:
  'diff@^7': '^8.0.3'
  'serialize-javascript@^6': '^7.0.5'
  'esbuild@^0.27': '^0.28.1'
  'js-yaml@^3': '^4.3.0'
  'js-yaml@^4': '^4.3.0'
  'sigstore@^4': '^4.1.1'
  'brace-expansion@^1': '^1.1.16'
  'brace-expansion@^2': '^2.1.2'
  'fast-uri@^3': '^3.1.4'
  'postcss@^8': '^8.5.18'
  'brace-expansion@^5': '^5.0.8'
  'tar@^7': '^7.5.21'
  'svgo@^4': '^4.0.2'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
linkWorkspacePackages: true
verifyDepsBeforeRun: false
