packages:
  - packages/*

allowBuilds:
  'esbuild': true
  'unrs-resolver': true
  'snyk': true

overrides:
  'brace-expansion@^5': '^5.0.8'
  'esbuild@^0.27': '^0.28.1'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
linkWorkspacePackages: true
verifyDepsBeforeRun: false
